apiVersion: skaffold/v2beta22
kind: Config
build:
  artifacts:
  - image: pay9/pay9-auth
    context: services/auth
    docker:
      dockerfile: Dockerfile.dev
  - image: pay9/pay9-frontend
    context: services/frontend
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile.dev
  - image: pay9/pay9-email
    context: services/email
    docker:
      dockerfile: Dockerfile.dev
  - image: pay9/pay9-expiration
    context: services/expiration
    docker:
      dockerfile: Dockerfile.dev
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - ./k8s/dev/*
